### ISSUE TITLE
Use ActivateOptions instead of Initialize

### ISSUE THREAD

**Issue by urielha** [eliranmoyal/ObjectsLogAppender#1]
hi,
Referring to TODO number 1
You can override the function ActivateOptions and log4net will call it on initialization.
like I am doing [here](https://github.com/urielha/log4net.ElasticSearch/blob/master/src/log4net.ElasticSearch/ElasticSearchAppender.cs#L69)
But I think you will have to call base.ActivateOptions() first.

**Comment by eliranmoyal** [comment]
Thanks Uriel!
working on it :)

**Comment by eliranmoyal** [comment]
worked like a charm :+1:
